sudo: required

language: node_js
node_js: 
  - "8"
  
services:
  - docker

before_install:
  - docker build -t manishtomer/docker-react -f Dockerfile.dev .

script:
  - docker run manishtomer/docker-react npm run test -- --coverage --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-630978305043"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY


